# For local development profile & properties only
# Other profiles will be read from config server for all other environments

spring:
  profiles:
    active: development

---

spring:
  profiles: development
  h2:
    console:
      enabled: true
      path: /h2 # http://localhost:8890/h2/
  datasource:
    url: jdbc:h2:file:~/test
    driver-class-name: org.h2.Driver
security:
  basic:
    enabled: false